# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.13.1
_src_path: gh:algorandfoundation/algokit-beaker-default-template
author_email: arsic2001sofija@gmail.com
author_name: Sofija
contract_name: guessing_word
deployment_language: python
preset_name: starter
project_name: PyTealWordGuessingGame-contracts

